### ISSUE TITLE
have individual workers log what they do

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#37]
right now `VolumeCreator#should_write_zip?` checks whether the source path is newer than the destination zip. That means that if we run a full refresh on the data set, it will queue a CreateJob for every volume in the set, which is a lot of extra work given that jobs are relatively expensive and checking the file time is relatively inexpensive. It also makes logging for incremental rsync (#10) more difficult if the plan is to log all jobs - since not all jobs actually result in a changed zip on disk. I know we were OK with the incremental being a superset of the actual changed volumes, but we should produce an incremental list that's actually useful.

Some alternatives to only enqueueing a job if the volume on disk has changed:
- provide a list of volumes to update instead of running against the entire dataset. That's potentially error prone since it would mean we need an independent (and likely untested) method of generating the set of volumes to update. 
- we could generate a list of changed volumes by having `VolumeCreator` do some logging itself (probably the easiest to reason about, not sure how easy actually having VolumeCreator do logging would be though)
- or by running a `find` on the filesystem after all jobs have completed (maybe a reasonable compromise?)

**Comment by malakai97** [comment]
So there are two issues here

1. Ensuring the usefulness of the incremental log
2. Performance

### On performance:

Based on the best benchmark I could find for resque, with 16 workers, each worker took 0.27 seconds to process a sinatra request. That puts us at 71 hours for the entire HT corpus assuming average job length is 0.27 seconds.  That could be completely off.  However, I would rather look to performance tweaks for resque than at changing the design before we really know if performance is going to be a problem.  

### Incremental Diffs:

When I argued for this specific imagining of incremental diffs, I was thinking about HTRC's need going forward--I did not account for trying to get them from the current, bad, unknown state to a good, known state.  My hope is that one large sync that requires only incremental syncs thereafter is tenable to them.  

### More Generally:

Enqueuing jobs based on the state of the filesystem is scary to me.  It opens us up to intermittent failures outside of the relative safety of the job-per-volume structure.  The fix for that is moving that decision elsewhere so that it can be treated like a data source like we're doing with feed and ht_rights.  I don't know of a good way of doing that for a filesystem.  Running and parsing a `find` over the corpus is too expensive/slow.  Maintaining our own database as a cache of that data seems like it could introduce a lot of complexity.

**Comment by aelkiss** [comment]
Performance: Let's try it and see. The option to disable forking for workers entirely for workers is straightforward and supported, so if performance is poor that's an easy first place to start.

Incremental diffs: I think they plan on running a full sync in June but want to do an incremental sync before that. Worst case we can plan on producing a list of changed files with find. I still think it would be useful to have the individual workers log, though.

Enqueuing jobs based on the state of the filesystem: I think it will only really matter for this first update, and I agree it isn't worth changing design decisions for that.

**Comment by aelkiss** [comment]
I think this is still going to be important, but for a slightly different reason.

The plan with providing the list of jobs queued should be fine for the creates - that shouldn't be too noisy.

The deletes will be a lot noisier since they will include lists of many things that were never in the dataset to begin with. We are supposed to provide notification to datasets users of things to delete from the datasets. Those will be significantly more useful if they only provide things that were actually deleted.
