### ISSUE TITLE
Don't overload "repository" term

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#55]
The "repository", in HT parlance, is where the source zips live. We should avoid any other use of that term in this project as it is leading to confusion.

**Comment by malakai97** [comment]
Let me prepend this with "if someone can think of names that are much better, sure let's ue them.

That said, I can't say I agree with the proposal.  "Repository" has a pretty clear definition in programming, and that's how we're using it.  The specific HT jargon mostly seems like shorthand born of HT only having one repository.

Responding to the comments from #51: 

> I think of "volume repo" as a repository of volumes. 

In mlibrary/datasets, Datasets::VolumeRepo is a repository of Dataset:Volume instances. The Volume class doesn't know anything about what is on disk.

> This is actually a mapping of the volume subset to the rights database? or in the case of the full set, the rights and rights and feed backend database?

I'm not sure I get the question so I'll try to be didactic.

We need to get our Volume instances from a VolumeRepo.  When we're instantiating a Scheduler to work on a subset, we give it a RightsVolumeRepo. When we're instantiating one for the superset, we'd also like to know about changes from feed, so we give it a RightsFeedVolumeRepo instead.  In both cases, the scheduler just knows it has a VolumeRepo.

I wouldn't say that it is a mapping of subset to the rights database.  VolumeRepos don't know anything about subsets.  Our calling code just knows that every subset needs information from the same VolumeRepo, and so that is the dependency that gets injected.

**Comment by aelkiss** [comment]
Yup, let's discuss this at some future point in time. Not urgent for now.

**Comment by aelkiss** [comment]
Won't fix. If we need to explicitly refer to the HathiTrust repository of volumes on disk, we can find a clear name for that that includes "repository" and an appropriate qualifier.
