### ISSUE TITLE
implement job_queue_empty?

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/datasets#57]
So we don't have multiple schedulers enqueuing jobs willy-nilly

**Comment by malakai97** [comment]
`Resque.size(queue_name_string)`

**Comment by malakai97** [comment]
Doing this just in the CLI doesn't cover us, because the usual case of running it as a service with resque-scheduler is going to bypass the cli.  

I think we might want to do this at both entry points, before the scheduler is invoked: in the cli, and in the SchedulerJob before it invokes the ReportManager.  That sort of indicates that they should both call out to something that encapsulates that.

**Comment by malakai97** [comment]
I should have something tomorrow morning that does what I was talking about above.
